import { KeylinkEvent } from '@/types';

export const mockEvents: KeylinkEvent[] = [
  {
    id: 'event-busan-120',
    title: '부산 로테이션 소개팅',
    region: 'busan',
    venue: '서면역 인근',
    venueAddress: '부산광역시 부산진구 부전동 (상세 장소는 개별 안내)',
    date: new Date('2026-04-26T14:00:00'),
    time: '14:00',
    maxMale: 8,
    maxFemale: 8,
    currentMale: 6,
    currentFemale: 7,
    price: 29000,
    originalPrice: 39000,
    currentPrice: 29000,
    status: 'open',
    description: '부산 서면역 인근 프리미엄 공간에서 진행되는 소규모 로테이션 소개팅입니다.',
    rankingOpen: false,
    matchingOpen: false,
    episode: 120,
    targetMaleAge: '94~98',
    targetFemaleAge: '94~98',
    createdAt: new Date(),
  },
  {
    id: 'event-busan-121',
    title: '부산 로테이션 소개팅',
    region: 'busan',
    venue: '서면역 인근',
    venueAddress: '부산광역시 부산진구 부전동 (상세 장소는 개별 안내)',
    date: new Date('2026-05-03T14:00:00'),
    time: '14:00',
    maxMale: 8,
    maxFemale: 8,
    currentMale: 2,
    currentFemale: 3,
    price: 29000,
    originalPrice: 39000,
    currentPrice: 29000,
    status: 'open',
    description: '부산 서면역 인근 프리미엄 공간에서 진행되는 소규모 로테이션 소개팅입니다.',
    rankingOpen: false,
    matchingOpen: false,
    episode: 121,
    targetMaleAge: '90~96',
    targetFemaleAge: '90~96',
    createdAt: new Date(),
  },
];

export const mockReviews = [
  {
    id: '1',
    couple: '김*수 ❤ 박*연',
    text: '처음엔 긴장했는데 진행이 너무 자연스러워서 금방 편안해졌어요. 덕분에 정말 좋은 분을 만났습니다. 2025년 6월에 키링크에서 만나서 이제 곧 1년이 돼요!',
    episode: '87기',
    region: '부산',
  },
  {
    id: '2',
    couple: '이*진 ❤ 최*호',
    text: '소규모라서 더 집중해서 대화할 수 있었어요. 8명이라 모든 분과 충분히 이야기를 나눌 수 있었고, 그 중에서 지금의 남자친구를 만났습니다 💛',
    episode: '101기',
    region: '부산',
  },
  {
    id: '3',
    couple: '오*현 ❤ 윤*서',
    text: '웹사이트에서 바로 예약하고 당일에 QR로 매칭 순위 입력까지. 디지털 시스템이 너무 편리해서 놀랐어요. 결과도 바로 확인할 수 있어서 두근두근했습니다 🥰',
    episode: '118기',
    region: '부산',
  },
];
