import { KeylinkEvent } from '@/types';

export const mockEvents: KeylinkEvent[] = [
  {
    id: 'event-busan-100',
    title: '부산 로테이션 소개팅',
    region: 'busan',
    venue: '파티룸 모노리 (Monory)',
    venueAddress: '부산시 해운대구 우동 1층',
    date: new Date('2026-04-26T14:00:00'),
    time: '14:00',
    maxMale: 8,
    maxFemale: 8,
    currentMale: 6,
    currentFemale: 7,
    price: 39000,
    status: 'open',
    description: '부산 해운대 프리미엄 파티룸 모노리에서 진행되는 소규모 로테이션 소개팅입니다.',
    rankingOpen: false,
    matchingOpen: false,
    episode: 102,
    createdAt: new Date(),
  },
  {
    id: 'event-busan-101',
    title: '부산 로테이션 소개팅',
    region: 'busan',
    venue: '파티룸 모노리 (Monory)',
    venueAddress: '부산시 해운대구 우동 1층',
    date: new Date('2026-05-03T14:00:00'),
    time: '14:00',
    maxMale: 8,
    maxFemale: 8,
    currentMale: 2,
    currentFemale: 3,
    price: 39000,
    status: 'open',
    description: '부산 해운대 프리미엄 파티룸 모노리에서 진행되는 소규모 로테이션 소개팅입니다.',
    rankingOpen: false,
    matchingOpen: false,
    episode: 103,
    createdAt: new Date(),
  },
  {
    id: 'event-changwon-55',
    title: '창원 로테이션 소개팅',
    region: 'changwon',
    venue: '카페 아뜰리에',
    venueAddress: '경남 창원시 성산구 상남동',
    date: new Date('2026-04-27T15:00:00'),
    time: '15:00',
    maxMale: 6,
    maxFemale: 6,
    currentMale: 5,
    currentFemale: 4,
    price: 39000,
    status: 'open',
    description: '창원 프리미엄 카페에서 진행되는 아늑한 소규모 소개팅입니다.',
    rankingOpen: false,
    matchingOpen: false,
    episode: 55,
    createdAt: new Date(),
  },
  {
    id: 'event-changwon-56',
    title: '창원 로테이션 소개팅',
    region: 'changwon',
    venue: '카페 아뜰리에',
    venueAddress: '경남 창원시 성산구 상남동',
    date: new Date('2026-05-10T15:00:00'),
    time: '15:00',
    maxMale: 6,
    maxFemale: 6,
    currentMale: 0,
    currentFemale: 1,
    price: 39000,
    status: 'upcoming',
    description: '창원 프리미엄 카페에서 진행되는 아늑한 소규모 소개팅입니다.',
    rankingOpen: false,
    matchingOpen: false,
    episode: 56,
    createdAt: new Date(),
  },
];

export const mockReviews = [
  {
    id: '1',
    couple: '김*수 ❤ 박*연',
    text: '처음엔 긴장했는데 진행이 너무 자연스러워서 금방 편안해졌어요. 덕분에 정말 좋은 분을 만났습니다. 2025년 6월에 키링크에서 만나서 이제 곧 1년이 돼요!',
    episode: '47기',
    region: '부산',
  },
  {
    id: '2',
    couple: '이*진 ❤ 최*호',
    text: '소규모라서 더 집중해서 대화할 수 있었어요. 8명이라 모든 분과 충분히 이야기를 나눌 수 있었고, 그 중에서 지금의 남자친구를 만났습니다 💛',
    episode: '61기',
    region: '부산',
  },
  {
    id: '3',
    couple: '정*아 ❤ 한*민',
    text: '창원에서 이런 퀄리티의 소개팅이 열린다는 것 자체가 신기했어요. 모노리 공간이 너무 예쁘고 편안해서 소개팅하기 딱 좋은 분위기였습니다!',
    episode: '32기',
    region: '창원',
  },
  {
    id: '4',
    couple: '오*현 ❤ 윤*서',
    text: '웹사이트에서 바로 예약하고 당일에 QR로 매칭 순위 입력까지. 디지털 시스템이 너무 편리해서 놀랐어요. 결과도 바로 확인할 수 있어서 두근두근했습니다 🥰',
    episode: '78기',
    region: '부산',
  },
];
